implemented shopping cart and ticket dao layers, shopping cart service
yutsevich/hibernate-cinema pull request #6
Opened 2020-10-09 08:53 UTC by yutsevich

2020-10-09 13:50 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
ця анотація тут зайва, адже ми використовуємо MapsId

2020-10-09 13:50 UTC, Sofasmile commented on src/main/java/com/dev/cinema/model/Ticket.java
> +    @OneToOne
чому ми тут використовуємо OneToOne?
На один сеанс в кіно може прийти тільки одна людина?

2020-10-09 13:50 UTC, Sofasmile commented on src/main/java/com/dev/cinema/service/impl/ShoppingCartServiceImpl.java
> +    public void registerNewShoppingCart(User user) {
цей метод варто використовувати в register()

2020-10-12 09:59 UTC, KseniiaMakarova requested changes
looks good 
please add testing to Main class and see if everything is ok

2020-10-12 13:25 UTC, KseniiaMakarova approved these changes

2020-10-12 13:25 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        User testShoppingCart = userService.findByEmail("ranger@gmail.com").get();
```suggestion
        User userFromDb = userService.findByEmail("ranger@gmail.com").get();
```

2020-10-12 13:27 UTC, merged